cargo-features=["edition2021"]
[package]
name = "db1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
rand_chacha = "0.3.1"
log = "*"
env_logger = "*"
cpython = {version = "*", optional = true}

[lib]
path="src/python-lib.rs"
crate-type=["cdylib"]
name="pythonlib"
required-features=["cpython"]

[features]
default=["cpython"]

[workspace]